raz_max_depth: 5.0
raz_thr: 256.0
nmp_margin: 120.0
nmp_scaling: 20.0
nmp_improving_scaling: 0.0
nmp_min_depth: 3.0
nmp_base_reduction: 4.0
nmp_reduction_scaling: 4.0
snmp_scaling: 85.0
lmr_min_searches: 5.0
lmr_min_depth: 3.0
lmr_red_constant: 0.7844
lmr_red_scaling: 2.4695
aspw_min_depth: 3.0
aspw_window_size: 50.0
aspw_widening_factor: 2.0
fp_base: 40.0
fp_scaling: 60.0
fp_max_depth: 8.0
fp_improving_margin: 0.0
rfp_scaling: 47.0
rfp_improving_scaling: 100.0
rfp_max_depth: 9.0
lmp_base: 4.0
lmp_lin_scaling: 4.0
lmp_quad_scaling: 0.0
lmp_max_depth: 5.0
cont_hist_scaling: 150.0
cont_hist_base: 125.0
cont_hist_malus_scaling: 1.0
