// config.rs
// All configurable thresholds for filtering and balancing.

pub struct FilterConfig {
    // ---------------------------------------------------------------- //
    // Score balance                                                      //
    // ---------------------------------------------------------------- //

    /// Minimum fraction of positions with score > 0 (STM-relative)
    /// Default: 0.50 — at least 50% positive scores
    pub min_positive_fraction: f64,

    /// Score threshold separating "quiet" from "material imbalance"
    /// Default: 100cp
    pub imbalance_threshold: i32,

    /// Minimum fraction of positions within [-imbalance_threshold, +imbalance_threshold]
    /// Default: 0.50 — at least 50% near-equal positions
    pub min_balanced_fraction: f64,

    /// Minimum fraction of positions outside [-imbalance_threshold, +imbalance_threshold]
    /// Default: 0.40 — at least 40% materially imbalanced
    pub min_imbalanced_fraction: f64,

    // ---------------------------------------------------------------- //
    // Hard filters — positions outside these ranges are always dropped  //
    // ---------------------------------------------------------------- //

    /// Drop positions with |score| above this (likely mate scores slipping through)
    /// Default: 3000cp
    pub max_score: i32,

    /// Drop positions with |score| below this (optional, 0 = disabled)
    pub min_score: i32,

    // ---------------------------------------------------------------- //
    // Pawn hash deduplication                                            //
    // ---------------------------------------------------------------- //

    /// Maximum number of positions allowed with the same pawn hash
    /// 0 = disabled
    pub max_per_pawn_hash: usize,

    // ---------------------------------------------------------------- //
    // Output                                                             //
    // ---------------------------------------------------------------- //

    /// Target number of positions in output. 0 = keep all that pass filters
    pub target_positions: usize,

    /// Option to filter on data generated by given network
    pub net_id : Option<u8>,

    /// Shuffle output before writing
    pub shuffle: bool,

    /// Random seed for reproducible shuffles. None = random seed
    pub shuffle_seed: Option<u64>,
}

impl FilterConfig {
    pub(crate) fn default() -> Self {
        Self {
            min_positive_fraction:  0.5,
            imbalance_threshold:    100,
            min_balanced_fraction:  0.5,
            min_imbalanced_fraction: 0.4,
            max_score:              2000,
            min_score:              0,
            max_per_pawn_hash:      0,
            target_positions:       0,
            net_id:                 None,
            shuffle:                true,
            shuffle_seed:           None,
        }
    }
}